// <auto-generated />
using System;
using DataAccess.EfCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.EfCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250120094025_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fa503ba-4510-41b4-a5cc-8fa54e532e17"),
                            Followers = 100,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("93d3ce8e-a58a-41eb-843f-59336600e5ab"),
                            Followers = 200,
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("522c9221-0e98-4b9f-b6ea-473bd01774d0"),
                            Name = "Project 1"
                        },
                        new
                        {
                            Id = new Guid("b544d7ae-1eb8-4fc9-81e4-f63e32c2caf3"),
                            Name = "Project 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
